### ISSUE TITLE
Unwishfull import of part of an object

### ISSUE THREAD

**Issue by polemidis** [kbwbe/A2plus#150]
I find a specific replicable bug. 
After a Part/Mirror is applied to a Part/Thickenss which was applied to a Body, that Body is showing when this file is imported. 
Steps to replicate
a) Got PD workbench, Create body. Create a sketch with a simple square
b) Pad it to a nice size so to look like  cube,
c) select to opposite faces, and with these selected got to Part/Thickness, give a minor NEGATIVE value. You should have a tube now in your screen,
d) Go to Part/Mirroring and mirror that Thickness to any plane. 
Save it. 
e) Open a new file and A2+/Add Part from external file and import the saved file from the previous step. 
What gets imported other the the Mirrored Thicknesses, is the Body too, which it shouldn't. Hiding it does not help. 

My apologies if thats a bug, and if I should follow a different route. Plz let me know.
Thank you!

**Comment by kbwbe** [comment]
Please update your release to V0.2.8

There is a new option in preferences: "do not import invisible shapes"
Activate this and restart A2plus.
Now you can set the "Body" to invisible, and it is not imported.

During tests, i used PartDesign-Thickness (instead of Part-Thickness), before doing part-mirror on the body. This worked without any changes to visibility.

Please test the new version.
Thank you for reporting this error.
