### ISSUE TITLE
Move part under rule of constraint not working

### ISSUE THREAD

**Issue by edsamuel57** [kbwbe/A2plus#430]
I created at a simple test to animate a few link segments in FreeCAD windows 10.  When I click the icon. The python console shows 'Gui.runCommand('a2p_MovePartUnderConstraints',0)'.  When I click the part to move.  Nothing happens.  I saved the file and opened it in my Ubuntu VM and it works great.  What am I missing in my installation.  Are there any Python dependencies I need to add?

![a2](https://user-images.githubusercontent.com/16006654/117376936-c3034c00-ae97-11eb-88d2-ff08c976bdc2.jpg)

**Comment by kbwbe** [comment]
Sorry, but i actually have no idea what's the problem here. You do not have to add any python modules to FC when using A2plus. Everything is already included. Unfortunately i cannot test on Windows, because I only have Linux machines here. Perhaps it is better when you post your problem and your files within the FC forum, so that a Windows guy can test them.
